### ISSUE TITLE
starting a node server

### ISSUE THREAD

**Issue by pankajtandon** [skwakman/nodejs-maven-plugin#1]
Hi,
Thanks for this plugin!
I'm looking for the ability to start a node server during a build because I need to run some Javascript tests during my build.

Do you have the capability to start a server (as against just extracting node) and then shut it (pretty much like jetty or cargo on the server). And I can place my test plugin in between?

I haven't looked thru the code yet.. looking for a short cut :)

Thanks!

**Comment by skwakman** [comment]
In it's current form this plugin only supports extracting a nodejs binary to the build environment. Running scripts is currently not supported, but it sounds like a good addition for a next release. 

In the mean time you might try to combine this plugin with the exec-maven-plugin (http://mojo.codehaus.org/exec-maven-plugin/). It might be possible to use this plugin to extract the nodejs executable and use exec-maven-plugin to run a script with it.

**Comment by b-long** [comment]
Any movement on this?  I hoping to eventually be able to build client-side code using [Grunt](http://gruntjs.com/), all invoked via Maven.  Thanks for the effort on this project @skwakman !

**Comment by skwakman** [comment]
To run grunt you'll need 'npm', the node package manager that is normally distributed alongside nodejs. Sadly, this plugin is only extracts the nodejs binary itself without npm module support. There's a separate issue filed for npm support (see https://github.com/skwakman/nodejs-maven-binaries/issues/1). Right now, my focus is on fixing this issue first.

When this issue is fixed, you'd be able to use this plugin alongside the exec-maven-plugin to run node processes using node modules. There are also some specialized grunt maven plugins out there (such as https://github.com/allegro/grunt-maven-plugin). 

While a simple 'execute this task' goal still sounds like a good addition for this plugin, these specialized plugins will probably be a better fit for running grunt tasks.

**Comment by skwakman** [comment]
Adding npm to the maven-provided node distribution has proven to be more difficult than previously thought. For more details, see https://github.com/skwakman/nodejs-maven-binaries/issues/1 .  I'm afraid I don't have any spare time left for this feature in the short term so I'm closing this bug for now. If anyone wants to provide patches I'll reopen it.

**Comment by robmazan** [comment]
I've just noticed this thread. I've created a solution for this a few months ago. I was using the maven-download-plugin to download npm. Anyone interested can checkout at: https://github.com/robmazan/maven-nodejs-sample
